Show which OVAL fails during parsing
When rule_dir_json.py runs as part of the build process (and invalid
OVALs are present), the build will fail with an error like:

    product has multiple remediations of the same type: sle12 - sle12.yml,sle15.yml
    product has multiple remediations of the same type: sle15 - sle12.yml,sle15.yml
    Traceback (most recent call last):
      File "/home/cipherboy/GitHub/cipherboy/ComplianceAsCode-content/utils/rule_dir_json.py", line 203, in <module>
        main()
      File "/home/cipherboy/GitHub/cipherboy/ComplianceAsCode-content/utils/rule_dir_json.py", line 173, in main
        rule_obj['ovals'], oval_products = handle_ovals(product_list, product_yamls, rule_obj)
      File "/home/cipherboy/GitHub/cipherboy/ComplianceAsCode-content/utils/rule_dir_json.py", line 98, in handle_ovals
        platforms = ssg.oval.applicable_platforms(oval_path)
      File "/home/cipherboy/GitHub/cipherboy/ComplianceAsCode-content/ssg/oval.py", line 126, in applicable_platforms
        raise e
      File "/home/cipherboy/GitHub/cipherboy/ComplianceAsCode-content/ssg/oval.py", line 122, in applicable_platforms
        oval_tree = ET.fromstring(header + body + footer)
      File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1347, in XML
        parser.feed(text)
    xml.etree.ElementTree.ParseError: mismatched tag: line 111, column 21

This makes it hard to find which OVAL actually caused the failure.

Add a line indicating such information to the user.

Signed-off-by: Alexander Scheel <alex.scheel@canonical.com>