bugfix: package_libselinux_installed: custom-package-removed.fail.sh: need to set releasever
+ rm -rf /var/lib/rpm/rpmdb.sqlite /var/lib/rpm/rpmdb.sqlite-shm /var/lib/rpm/rpmdb.sqlite-wal
+ rpm --initdb
+ grep -q rhel /etc/os-release
+ dnf install -y fedora-release
Unable to detect release version (use '--releasever' to specify release version)
...
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=x86_64 (IP: ...)