Add a dummy severity and rationaly to linux_os/guide/system/network/network-ipv6/configuring_ipv6/disabling_ipv6_autoconfig/rule.yml
This rule was disabled (documentation_complete:false) but had no
severity or rationale. This was preventing building with --debug,
because the build them failed with:

[  1%] [ocp4-content] generating shorthand.xml
Traceback (most recent call last):
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 758, in from_yaml
    rule._set_attributes_from_dict(yaml_contents)
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 887, in _set_attributes_from_dict
    raise value
RuntimeError: Missing key 'rationale'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jhrozek/devel/compliance-as-code-content/build-scripts/yaml_to_shorthand.py", line 89, in <module>
    main()
  File "/home/jhrozek/devel/compliance-as-code-content/build-scripts/yaml_to_shorthand.py", line 71, in main
    loader.process_directory_tree(benchmark_root, add_content_dirs)
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 1125, in process_directory_tree
    self._load_group_process_and_recurse(start_dir)
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 1118, in _load_group_process_and_recurse
    self._recurse_into_subdirs()
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 1131, in _recurse_into_subdirs
    loader.process_directory_tree(subdir)
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 1125, in process_directory_tree
    self._load_group_process_and_recurse(start_dir)
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 1118, in _load_group_process_and_recurse
    self._recurse_into_subdirs()
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 1131, in _recurse_into_subdirs
    loader.process_directory_tree(subdir)
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 1125, in process_directory_tree
    self._load_group_process_and_recurse(start_dir)
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 1118, in _load_group_process_and_recurse
    self._recurse_into_subdirs()
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 1131, in _recurse_into_subdirs
    loader.process_directory_tree(subdir)
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 1125, in process_directory_tree
    self._load_group_process_and_recurse(start_dir)
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 1118, in _load_group_process_and_recurse
    self._recurse_into_subdirs()
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 1131, in _recurse_into_subdirs
    loader.process_directory_tree(subdir)
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 1125, in process_directory_tree
    self._load_group_process_and_recurse(start_dir)
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 1119, in _load_group_process_and_recurse
    self._process_rules()
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 1165, in _process_rules
    rule = Rule.from_yaml(rule_yaml, self.env_yaml)
  File "/home/jhrozek/devel/compliance-as-code-content/ssg/build_yaml.py", line 762, in from_yaml
    raise RuntimeError(msg)
RuntimeError: Error processing '/home/jhrozek/devel/compliance-as-code-content/linux_os/guide/system/network/network-ipv6/configuring_ipv6/disabling_ipv6_autoconfig/rule.yml': Missing key 'rationale'
make[2]: *** [ocp4/CMakeFiles/generate-internal-ocp4-shorthand.xml.dir/build.make:2129: ocp4/shorthand.xml] Error 1
make[1]: *** [CMakeFiles/Makefile2:1094: ocp4/CMakeFiles/generate-internal-ocp4-shorthand.xml.dir/all] Error 2
make: *** [Makefile:151: all] Error 2

Let's add a dummy value for both so that the debug builds work at all.