[Infrastructure] [shared/product-make.include] Change the order of prerequisities for the "$(OUT)/xccdf-unlinked-final.xml" target in order all products to currently end up with the warning:
  Error: Can't locate remediation ("<fix system") elements in "output/xccdf-unlinked-withremediations.xml". Exiting!

which is the actual state (remediations aren't currently included
in any of the benchmarks)