Fix traceback when SRG doesn't exist
Addressing:

```
jcerny@fedora:~/work/git/scap-security-guide (rhel10_stig_manual)$  utils/build_stig_control.py -o products/rhel10/controls/stig_rhel10.yml -p rhel10 -m shared/references/disa-stig-rhel10-v1r1-xccdf-manual.xml -g controls/srg_gpos.yml
Traceback (most recent call last):
  File "/home/jcerny/work/git/scap-security-guide/utils/build_stig_control.py", line 232, in <module>
    main()
    ~~~~^^
  File "/home/jcerny/work/git/scap-security-guide/utils/build_stig_control.py", line 204, in main
    controls = get_controls(known_rules, ns, root, srg_controls)
  File "/home/jcerny/work/git/scap-security-guide/utils/build_stig_control.py", line 158, in get_controls
    control['rules'] = get_rules_for_control(stig_id, known_rules, srgs, srg_controls)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jcerny/work/git/scap-security-guide/utils/build_stig_control.py", line 139, in get_rules_for_control
    rule_set.update(srg_controls.get_control(srg).rules)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/jcerny/work/git/scap-security-guide/ssg/controls.py", line 688, in get_control
    raise ValueError(msg) from None
ValueError: SRG-OS-000142-GPOS-00072 not found in policy srg_gpos
```