Fix SLE16 build failure
Addressing:
jinja2.exceptions.UndefinedError: 'sshd_oval_check_usr' is undefined

The PR https://github.com/ComplianceAsCode/content/pull/14439 merged
today removed this macro sshd_oval_check_usr and all its occurrences.
But, the https://github.com/ComplianceAsCode/content/pull/14831 merged
yesterday added one occurrence of this macro back. And the first PR
wasn't rebased after the latter was merged.