[BugFix] [JRE] Truly move oval-fix-test-attestation-urls.xslt XSLT transformation from Java to JRE product
The current 'master' has the following bug when building JRE content
e.g. on RHEL-7:
<pre>
..
make[1]: Leaving directory `/root/scap-security-guide/rpmbuild/BUILD/scap-security-guide-0.1.22/RHEL/7'
+ cd JRE
+ make dist
make[1]: Entering directory `/root/scap-security-guide/rpmbuild/BUILD/scap-security-guide-0.1.22/JRE'
..
xsltproc -o output/ssg-jre-oval.xml transforms/oval-fix-test-attestation-urls.xslt output/ssg-jre-oval.xml
warning: failed to load external entity "transforms/oval-fix-test-attestation-urls.xslt"
cannot parse transforms/oval-fix-test-attestation-urls.xslt
make[1]: *** [content] Error 4
make[1]: Leaving directory `/root/scap-security-guide/rpmbuild/BUILD/scap-security-guide-0.1.22/JRE'
error: Bad exit status from /root/scap-security-guide/rpmbuild/rpm-tmp.MaH6kr (%build)

RPM build errors:
    Bad exit status from /root/scap-security-guide/rpmbuild/rpm-tmp.MaH6kr (%build)
make: *** [rpm] Error 1
</pre>

This is because 'oval-fix-test-attestation-urls.xslt' still wasn't moved from former 'Java'
to new 'JRE' product path, as can be seen below:

<pre>
$ find . -name oval-fix-test-attestation-urls.xslt
./Webmin/transforms/oval-fix-test-attestation-urls.xslt
./RHEVM3/transforms/oval-fix-test-attestation-urls.xslt
./RHEL/7/transforms/oval-fix-test-attestation-urls.xslt
./RHEL/6/transforms/oval-fix-test-attestation-urls.xslt
./RHEL/5/transforms/oval-fix-test-attestation-urls.xslt
./OpenStack/transforms/oval-fix-test-attestation-urls.xslt
./Java/transforms/oval-fix-test-attestation-urls.xslt
./Firefox/transforms/oval-fix-test-attestation-urls.xslt
./Fedora/transforms/oval-fix-test-attestation-urls.xslt
./Chromium/transforms/oval-fix-test-attestation-urls.xslt
</pre>

The movement should happen within https://github.com/OpenSCAP/scap-security-guide/pull/582 but
looks as I rebased that PR to current 'master' in that time, the 'oval-fix-test-attestation-urls.xslt'
transformation got moved back to the original 'Java/transforms' directory.

Therefore truly move the 'oval-fix-test-attestation-urls.xslt' XLST transformation into new
'JRE/transforms' location, which fixes the aforementioned issue.